name: Playwright Test

on:
  workflow_dispatch:  # Allows manual trigger from GitHub Actions tab

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install playwright
          playwright install --with-deps

      - name: Run Playwright script
        run: python test_example.py
