name: Playwright Test

on:
  workflow_dispatch:  # Manual trigger

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      APP_URL: ${{ secrets.APP_URL }}
      BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
      CHAT_ID: ${{ secrets.CHAT_ID }}
      USER_ID: ${{ secrets.USER_ID }}
      USER_PIN: ${{ secrets.USER_PIN }}
      ALLOWED_LOCS: ${{ secrets.ALLOWED_LOCS }}
      ALLOWED_CLS: ${{ secrets.ALLOWED_CLS }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: "pip"

      - name: Cache Playwright browsers
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          playwright install --with-deps

      - name: Run Playwright script
        continue-on-error: true
        run: python main.py

      - name: Trigger new workflow run
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $GITHUB_TOKEN" \
            https://api.github.com/repos/ravi409/sudharsana-chakram/actions/workflows/playwright.yml/dispatches \
            -d '{"ref":"main"}'

